#!/bin/bash

XML2=/usr/bin/xml2
UNZIP=/usr/bin/unzip
SED=/bin/sed
#Gawk is probably necessary over plain awk
GAWK=/usr/bin/gawk

do_help() {
	while [ "$#" -gt 0 ]
	do
		echo "Error: $1">>/dev/stderr
		shift
	done

	cat <<EOF >&2
Syntax: ods2tsv [-q -d] <sheet> [file]
Syntax: ods2tsv [-l] [file]

In normal use the input file (stdin if not specified) should be an ODS 
document. This script will print the sheet named in tab delimited form.

Valid options:

 --quiet -q     Don't display warnings about empty/missing sheets.
 --debug -d     Print far too much information
 --list  -l     List all sheets (sheets per line)

EOF
	exit 2
}

QUIET=0
DEBUG=0
LIST=0
while [[ "$1" = -* ]]
do
	case $1 in
		-q|--quiet)
			QUIET=1
			;;
		-d|--debug)
			DEBUG=1
			;;
		-l|--list)
			LIST=1
			;;
		-h|--help)
			do_help
			;;
		*)
			do_help "Invalid option: $1"
			;;
	esac
	shift
done

for PROG in XML2 UNZIP SED GAWK
do
	PROGLC=${PROG,,}
	test -e "${!PROG}" || declare $PROG=`which $PROGLC`
	if [ ! -e "${!PROG}" ]
	then
		echo "Please set $PROG. ${!PROG} doesn't seem to be an executable file"
	fi
	test "$DEBUG" -eq 1 && echo $PROG is ${!PROG} >&2
done

dump_content() {
	if [ -e "$1" ]
	then
		"$UNZIP" -p "$1" content.xml|
			"$XML2"|
			#We use sed just to make things a little less verbose by picking out lines we don't care about and truncating the line prefix
			"$SED" '/^\/office:document-content\/office:body\/office:spreadsheet\/table:table/ {s///g;b};d'
		PIPESTATUSSAVED=( ${PIPESTATUS[*]} )
		if [ ${PIPESTATUSSAVED[0]} -ne 0 -o ${PIPESTATUSSAVED[1]} -ne 0 -o ${PIPESTATUSSAVED[2]} -ne 0 ]
		then
			echo "Error processing $1. unzip status: ${PIPESTATUSSAVED[0]}, xml2 status: ${PIPESTATUSSAVED[1]}, sed status: ${PIPESTATUSSAVED[2]}">&2
			exit 1
		fi
	else
		echo "Error. File not found: $1">&2
		exit 2
	fi
}

normal_operation() {
	dump_content "$INPUT"|
		awk "-vSHEET=$SHEET" "-vQUIET=$QUIET" "-vINPUT=$INPUT" "-vDEBUG=$DEBUG" '
/^\/@table:name=/ {
	correct_sheet=0
}

$0 ~ ("^/@table:name=" SHEET "$") {
	if((already_found_correct_sheet==1) && (!QUIET)) {
		warn("Duplicate sheet " SHEET "?")
	}
	correct_sheet=1
	already_found_correct_sheet=1
	row_init()
}

!correct_sheet {
	next
}

DEBUG {print}

/\/table:table-row\/@table:number-rows-repeated=/ {
	gsub("^/table:table-row/@table:number-rows-repeated=", "")
	row_repeat=$0
}

/^\/table:table-row\/table:table-cell$/ {
	if(col_repeat>0) {
		#We have unprinted (and therefore blank) cells. If it turns out there are no data cells remaining then we wont print them.
		pending_blank_cols+=col_repeat
	}
	col_repeat=1
}
/^\/table:table-row\/table:table-cell\/@table:number-columns-repeated=/ {
	gsub("^/table:table-row/table:table-cell/@table:number-columns-repeated=", "")
	col_repeat=$0
}

function row_init() {
	pending_blank_cols=0
	row_repeat=1
	col_repeat=1
	row_output=""
	sent_output=1
}

function warn(msg) {
	print "ods2tsv: " msg " in " INPUT > "/dev/stderr"
}

/^\/table:table-row$/ {
	#Row delimiter
	if(row_output) {
		for(;pending_blank_rows;pending_blank_rows--) {
			print "";
		}
		#Each line will have a trailing tab
		gsub(/\t+$/, "", row_output);
		for (;row_repeat;row_repeat--) {
			printf("%s\n", row_output)
		}
	}else{
		pending_blank_rows+=row_repeat;
	}

	row_init()
}

/^\/table:table-row\/table:table-cell\/text/ {
	gsub ("^/table:table-row/table:table-cell/text:p=", "")
	for(;pending_blank_cols;pending_blank_cols--) {
		row_output=row_output "\t"
	}
	for(;col_repeat;col_repeat--) {
		gsub(/\t/, " ")
		#Its easier to just remove this trailing tab for the last field!
		row_output=row_output $0 "\t"
	}
}

END {
	if((already_found_correct_sheet!=1) && (!QUIET)) {
		warn("Failed to find sheet named " SHEET)
	}
}
'
}

if [ "$LIST" -eq 1 ]
then
	if [ "$#" -gt "1" ]
	then
		do_help "Expected at most a file name"
	fi

	INPUT="$1"
	test "$INPUT" || INPUT=/dev/stdin
	dump_content "$INPUT"|"$SED" '/^\/@table:name=/ {s///g;b};d'
else
	if [ "$#" -lt "1" -o "$#" -gt "2" ]
	then
		do_help "Expected a sheet name, (and possibly a file name)"
	fi

	SHEET=$1
	INPUT="$2"
	test "$INPUT" || INPUT=/dev/stdin
	normal_operation
fi

